language: java
jdk:
- openjdk7
- oraclejdk7
install: mvn clean install -DskipTests=true
notifications:
  hipchat:
    rooms:
      secure: fra2NitsktOSOmuU6uudcnzlBHqd50ryp745BRzHanqpmbKgYQ7Y8UqsGaNsw8uyTGOiUGAzX59BytP/AcNjo7KHavBLH5HbnH8CQBOtiCuyagDjWedh2egIg+vZJJVXaB6LU1aeiDiSc8sT/7Bf8ZBpc/udolci+3dCOzt6zxM=
