language: java
jdk:
- openjdk7
- oraclejdk7
install: mvn clean install -DskipTests=true
notifications:
  hipchat:
    rooms:
      secure: fra2NitsktOSOmuU6uudcnzlBHqd50ryp745BRzHanqpmbKgYQ7Y8UqsGaNsw8uyTGOiUGAzX59BytP/AcNjo7KHavBLH5HbnH8CQBOtiCuyagDjWedh2egIg+vZJJVXaB6LU1aeiDiSc8sT/7Bf8ZBpc/udolci+3dCOzt6zxM=
deploy:
  provider: releases
  api_key:
    secure: ANP83a3bGRYnIc0yn+HRt67FcgEoN02ufPYTsyXpT0USzmmLIxFCnDoA36neJYnXQajFrH82sJ0OPLO6utdkKp3RPeZwynQvnGgFMQl71Brzm+xygRRDk//zQo+DYKyH0XttXtQdO377ahLoTpEw8YIjytpue06xrxMw/y39biM=
  file: target/*.jar
  on:
    repo: jose-gonzales/stash-jenkins-postreceive-webhook
